### ISSUE TITLE
安装出错。

### ISSUE THREAD

**Issue by 22044075** [YaoFANGUK/video-subtitle-extractor#1]
(videoEnv) D:\Users\video-subtitle-extractor-main\video-subtitle-extractor-main>pip install -r requirements(win).txt
Requirement 'tensorflow @ https://github.com/fo40225/tensorflow-windows-wheel/raw/master/1.4.0/py36/GPU/cuda91cudnn7avx2/tensorflow_gpu-1.4.0-cp36-cp36m-win_amd64.whl' looks like a filename, but the file does not exist
Exception:
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\videoEnv\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "D:\ProgramData\Anaconda3\envs\videoEnv\lib\site-packages\pip\commands\install.py", line 312, in run
    wheel_cache
  File "D:\ProgramData\Anaconda3\envs\videoEnv\lib\site-packages\pip\basecommand.py", line 295, in populate_requirement_set
    wheel_cache=wheel_cache):
  File "D:\ProgramData\Anaconda3\envs\videoEnv\lib\site-packages\pip\req\req_file.py", line 93, in parse_requirements
    for req in req_iter:
  File "D:\ProgramData\Anaconda3\envs\videoEnv\lib\site-packages\pip\req\req_file.py", line 158, in process_line
    isolated=isolated, options=req_options, wheel_cache=wheel_cache
  File "D:\ProgramData\Anaconda3\envs\videoEnv\lib\site-packages\pip\req\req_install.py", line 211, in from_line
    link = Link(path_to_url(p))
  File "D:\ProgramData\Anaconda3\envs\videoEnv\lib\site-packages\pip\download.py", line 465, in path_to_url
    url = urllib_parse.urljoin('file:', urllib_request.pathname2url(path))
  File "D:\ProgramData\Anaconda3\envs\videoEnv\lib\nturl2path.py", line 60, in pathname2url
    raise OSError(error)
OSError: Bad path: D:\Users\video-subtitle-extractor-main\video-subtitle-extractor-main\tensorflow @ https:\github.com\fo40225\tensorflow-windows-wheel\raw\master\1.4.0\py36\GPU\cuda91cudnn7avx2\tensorflow_gpu-1.4.0-cp36-cp36m-win_amd64.whl
You are using pip version 9.0.1, however version 20.2.4 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by YaoFANGUK** [comment]
试试直接把requirements(win).txt的 *tensorflow @ https://github.com/fo40225/tensorflow-windows-wheel/raw/master/1.4.0/py36/GPU/cuda91cudnn7avx2/tensorflow_gpu-1.4.0-cp36-cp36m-win_amd64.whl* 这行删了，然后再控制台手动尝试安装tensorflow：
```
pip install https://github.com/fo40225/tensorflow-windows-wheel/raw/master/1.4.0/py36/GPU/cuda91cudnn7avx2/tensorflow_gpu-1.4.0-cp36-cp36m-win_amd64.whl 
```
如果安装成功了，再执行 
```
pip install -r requirements(win).txt 
```

如果直接浏览器访问不了<a href="https://github.com/fo40225/tensorflow-windows-wheel/raw/master/1.4.0/py36/GPU/cuda91cudnn7avx2/tensorflow_gpu-1.4.0-cp36-cp36m-win_amd64.whl"> https://github.com/fo40225/tensorflow-windows-wheel/raw/master/1.4.0/py36/GPU/cuda91cudnn7avx2/tensorflow_gpu-1.4.0-cp36-cp36m-win_amd64.whl</a>的话应该是网络的问题，尝试科学上网环境
