### ISSUE TITLE
所有版本都无法运行

### ISSUE THREAD

**Issue by BugKun** [YaoFANGUK/video-subtitle-extractor#108]
AMD 3800X CPU Win10系统

使用GPU版里的`debug.cmd`启动

报错信息如下
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "Z:\vse_windows_GPU\Python\lib\site-packages\qpt\run.py", line 13, in <module>
    module.run()
  File "Z:\vse_windows_GPU\Python\lib\site-packages\qpt\executor.py", line 519, in run
    lib = importlib.import_module(main_lib_path)
  File "Z:\vse_windows_GPU\Python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "Z:\vse_windows_GPU\resources\gui.py", line 15, in <module>
    import PySimpleGUI as sg
  File "Z:\vse_windows_GPU\Python\lib\site-packages\PySimpleGUI\__init__.py", line 2, in <module>
    from .PySimpleGUI import *
  File "Z:\vse_windows_GPU\Python\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 125, in <module>
    tclversion_detailed = tkinter.Tcl().eval('info patchlevel')
  File "Z:\vse_windows_GPU\Python\lib\tkinter\__init__.py", line 2372, in Tcl
    return Tk(screenName, baseName, className, useTk)
  File "Z:\vse_windows_GPU\Python\lib\tkinter\__init__.py", line 2270, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable init.tcl in the following directories:
    {D:\CSR\BlueSuite 2.6.8} Z:/vse_windows_GPU/Python/lib/tcl8.6 Z:/vse_windows_GPU/lib/tcl8.6 Z:/lib/tcl8.6 Z:/vse_windows_GPU/library Z:/library Z:/tcl8.6.9/library Z:/tcl8.6.9/library



This probably means that Tcl wasn't installed properly.
```

**Comment by BugKun** [comment]
> Win10系统

就是Win10系统

**Comment by BugKun** [comment]
换了台电脑试了一下，是不是不支持英文系统？

**Comment by BugKun** [comment]
找到问题了
https://github.com/apprenticeharper/DeDRM_tools/issues/86
