### ISSUE TITLE
停止不动，是怎么回事？ 微信nlanguage

### ISSUE THREAD

**Issue by nissansz** [YaoFANGUK/video-subtitle-extractor#112]
programmer(nissansz@qq.com)  17:09:17
L:\>python L:\jpdrama\video-subtitle-extractor-main\backend\main.py
Running Verify Fluid Program ...
Your Paddle Fluid works well on SINGLE GPU or CPU.
W0418 17:05:02.352984 65100 fuse_all_reduce_op_pass.cc:76] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 1.
Your Paddle Fluid works well on MUTIPLE GPU or CPU.
Your Paddle Fluid is installed successfully! Let's start deep Learning with Paddle Fluid now
请输入视频完整路径：Shoujiki.Fudousan.Ep01.Chi_Jap.HDTVrip.1280X720-cut_0003_0001.mp4
请指定字幕区域 (ymin ymax xmin xmax)：616 673 0 1280
E0418 17:05:41.080835 65100 analysis_config.cc:91] Please compile with gpu to EnableGpu()
识别字幕语言：ch
识别模式：fast
帧数：0.0，帧率：0.0
【处理中】开启提取视频关键帧...
Traceback (most recent call last):
  File "L:\jpdrama\video-subtitle-extractor-main\backend\main.py", line 920, in <module>
    se.run()
  File "L:\jpdrama\video-subtitle-extractor-main\backend\main.py", line 130, in run
    self.extract_frame_by_vsf()
  File "L:\jpdrama\video-subtitle-extractor-main\backend\main.py", line 330, in extract_frame_by_vsf
    top_end = 1 - self.sub_area[0] / self.frame_height
ZeroDivisionError: division by zero
Running Verify Fluid Program ...
Your Paddle Fluid works well on SINGLE GPU or CPU.
W0418 17:05:44.840761 48028 fuse_all_reduce_op_pass.cc:76] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 1.
Your Paddle Fluid works well on MUTIPLE GPU or CPU.
Your Paddle Fluid is installed successfully! Let's start deep Learning with Paddle Fluid now

programmer(nissansz@qq.com)  17:09:32
停在这里不动了，是怎么回事？

![image](https://user-images.githubusercontent.com/41010669/163785965-587dea7d-f9cb-4298-a3af-05c553272b40.png)

**Comment by nissansz** [comment]
视频路径没写完整，写完整即可
