### ISSUE TITLE
在Ubuntu服务器上运行时，raw.txt文件找不到

### ISSUE THREAD

**Issue by hongfeixue** [YaoFANGUK/video-subtitle-extractor#123]
Traceback (most recent call last):
  File "backend/main.py", line 1021, in <module>
    task("/home/disk2/tyxu/video-subtitle-extractor/test/test_cn.mp4")
  File "backend/main.py", line 1009, in task
    se.run()
  File "backend/main.py", line 184, in run
    self.generate_subtitle_file()
  File "backend/main.py", line 531, in generate_subtitle_file
    subtitle_content = self._remove_duplicate_subtitle()
  File "backend/main.py", line 738, in _remove_duplicate_subtitle
    self._concat_content_with_same_frameno()
  File "backend/main.py", line 796, in _concat_content_with_same_frameno
    with open(self.raw_subtitle_path, mode='r', encoding='utf-8') as r:
FileNotFoundError: [Errno 2] No such file or directory: '/home/disk2/tyxu/video-subtitle-extractor/output/test_cn/subtitle/raw.txt'
/home/environment/hfxue/anaconda3/envs/videoEnv/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.w

**Comment by YaoFANGUK** [comment]
跑的gui还是cli

**Comment by hongfeixue** [comment]
CLI
python ./backend/main.py

**Comment by hongfeixue** [comment]
> 跑的gui还是cli

python ./backend/main.py

**Comment by YaoFANGUK** [comment]
sudo执行试试
