### ISSUE TITLE
gpu运行时出现错误，OSError: (External) CUDA error(3), initialization error.    [Hint: 'cudaErrorInitializationError'. The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:284)

### ISSUE THREAD

**Issue by Zhipeng-Ye** [YaoFANGUK/video-subtitle-extractor#135]
Traceback (most recent call last):
  File "/home/yezhipeng/.conda/envs/ocr_3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/yezhipeng/.conda/envs/ocr_3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/user/yezhipeng/video-subtitle-extractor/backend/tools/subtitle_ocr.py", line 123, in recv_video_frame_handle
    text_recogniser = OcrRecogniser()
  File "/mnt/user/yezhipeng/video-subtitle-extractor/backend/tools/ocr.py", line 13, in __init__
    self.recogniser = self.init_model()
  File "/mnt/user/yezhipeng/video-subtitle-extractor/backend/tools/ocr.py", line 96, in init_model
    return TextSystem(self.args)
  File "/mnt/user/yezhipeng/video-subtitle-extractor/backend/tools/infer/predict_system.py", line 46, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "/mnt/user/yezhipeng/video-subtitle-extractor/backend/tools/infer/predict_det.py", line 119, in __init__
    self.predictor, self.input_tensor, self.output_tensors, self.config = utility.create_predictor(
  File "/mnt/user/yezhipeng/video-subtitle-extractor/backend/tools/infer/utility.py", line 316, in create_predictor
    predictor = inference.create_predictor(config)
OSError: (External) CUDA error(3), initialization error. 
  [Hint: 'cudaErrorInitializationError'. The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:284)

**Comment by Zhipeng-Ye** [comment]
直接运行了源码，显卡是p100，cuda11.2

**Comment by Zhipeng-Ye** [comment]
我查了一下好像是说，paddle在多线程运行的时候，要在子线程内单独引入paddle，但是我尝试了一下，好像没有用https://github.com/PaddlePaddle/PaddleDetection/issues/2241

**Comment by YaoFANGUK** [comment]
```python
    multiprocessing.set_start_method("spawn")
```
应该是多进程的时候要单独引入paddle，项目里面已经单独为每个进程创建资源，但是显存占用会很大。

**Comment by Zhipeng-Ye** [comment]
谢谢，目前没什么问题了
