### ISSUE TITLE
ModuleNotFoundError: No module named 'pyexpat'

### ISSUE THREAD

**Issue by actforjason** [YaoFANGUK/video-subtitle-extractor#150]

**Comment by actforjason** [comment]
> >"./Python/python.exe" -c "import sys;sys.path.append('./Python');sys.path.append('./Python/Lib');sys.path.append('./Python/Lib/site-packages');sys.path.append('./Python/Scripts');import qpt.run as run"
> Traceback (most recent call last):
>   File "B:\MediaTools\vse\Python\Lib\site-packages\qpt\kernel\qcode.py", line 12, in <module>
>     from pip._internal.utils.misc import get_installed_distributions
>   File "B:\MediaTools\vse\Python\Lib\site-packages\pip\_internal\utils\misc.py", line 35, in <module>
>     from pip._vendor.pkg_resources import Distribution
>   File "B:\MediaTools\vse\Python\Lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 35, in <module>
>     import plistlib
>   File "B:\MediaTools\vse\Python\Lib\plistlib.py", line 65, in <module>
>     from xml.parsers.expat import ParserCreate
>   File "B:\MediaTools\vse\Python\Lib\xml\parsers\expat.py", line 4, in <module>
>     from pyexpat import *
> ModuleNotFoundError: No module named 'pyexpat'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "B:\MediaTools\vse\Python\Lib\site-packages\qpt\run.py", line 22, in <module>
>     from qpt.executor import RunExecutableModule
>   File "B:\MediaTools\vse\Python\Lib\site-packages\qpt\executor.py", line 20, in <module>
>     from qpt.modules.package import QPTDependencyPackage, QPTGUIDependencyPackage, \
>   File "B:\MediaTools\vse\Python\Lib\site-packages\qpt\modules\package.py", line 13, in <module>
>     from qpt.kernel.qcode import PythonPackages
>   File "B:\MediaTools\vse\Python\Lib\site-packages\qpt\kernel\qcode.py", line 14, in <module>
>     from pip._internal.utils.misc import cast
>   File "B:\MediaTools\vse\Python\Lib\site-packages\pip\_internal\utils\misc.py", line 35, in <module>
>     from pip._vendor.pkg_resources import Distribution
>   File "B:\MediaTools\vse\Python\Lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 35, in <module>
>     import plistlib
>   File "B:\MediaTools\vse\Python\Lib\plistlib.py", line 65, in <module>
>     from xml.parsers.expat import ParserCreate
>   File "B:\MediaTools\vse\Python\Lib\xml\parsers\expat.py", line 4, in <module>
>     from pyexpat import *
> ModuleNotFoundError: No module named 'pyexpat'

**Comment by actforjason** [comment]
用源码没有问题

**Comment by YaoFANGUK** [comment]
看上去是qpt的问题
