### ISSUE TITLE
运行gui.py 的时候出现错误了。。。

### ISSUE THREAD

**Issue by vvlaw** [YaoFANGUK/video-subtitle-extractor#164]
OS: Archlinux

python gui.py                                                                                  ✔  4610  09:05:08
Error: Can not import avx core while this file exists: /home/vvlaw/ENTER/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/core_avx.so
Traceback (most recent call last):
  File "gui.py", line 8, in <module>
    import backend.main
  File "/home/vvlaw/video-subtitle-extractor/backend/main.py", line 25, in <module>
    import config
  File "/home/vvlaw/video-subtitle-extractor/backend/config.py", line 16, in <module>
    from paddle import fluid
  File "/home/vvlaw/ENTER/envs/videoEnv/lib/python3.8/site-packages/paddle/__init__.py", line 25, in <module>
    from .fluid import monkey_patch_variable
  File "/home/vvlaw/ENTER/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/vvlaw/ENTER/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/home/vvlaw/ENTER/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/core.py", line 294, in <module>
    raise e
  File "/home/vvlaw/ENTER/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/core.py", line 256, in <module>
    from .core_avx import *
ImportError: /home/vvlaw/ENTER/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/core_avx.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE

**Comment by vvlaw** [comment]
通过安装paddle 2.4.0得到解决。
pip install paddlepaddle==2.4.0rc0

不过好像不能启动Gui?
Running Verify Fluid Program ...
Your Paddle Fluid works well on SINGLE GPU or CPU.
/home/vvlaw/ENTER/envs/videoEnv/lib/python3.8/site-packages/paddle/fluid/executor.py:1583: UserWarning: Standalone executor is not used for data parallel
  warnings.warn(
W1006 15:36:55.345504 12427 fuse_all_reduce_op_pass.cc:79] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 1.
Your Paddle Fluid works well on MUTIPLE GPU or CPU.
Your Paddle Fluid is installed successfully! Let's start deep Learning with Paddle Fluid now
3000 2000
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  45 (X_OpenFont)
  Value in failed request:  0x340008d
  Serial number of failed request:  973
  Current serial number in output stream:  974
