### ISSUE TITLE
Mac电脑运行异常,提示Can't find a usable init.tcl in the following directories

### ISSUE THREAD

**Issue by dfvips** [YaoFANGUK/video-subtitle-extractor#179]
电脑：Macbook Pro M2
系统：MacOs 13.0.1
日志：
./vse  
Traceback (most recent call last):
  File "/var/folders/y3/8xn_btkd7476nynq0r29rv7r0000gn/T//onefile_38144_1671365304_810716/gui.py", line 15, in <module>
  File "/var/folders/y3/8xn_btkd7476nynq0r29rv7r0000gn/T/onefile_38144_1671365304_810716/dependencies/PySimpleGUI/__init__.py", line 2, in <module>
    from .PySimpleGUI import *
  File "/var/folders/y3/8xn_btkd7476nynq0r29rv7r0000gn/T/onefile_38144_1671365304_810716/dependencies/PySimpleGUI/PySimpleGUI.py", line 125, in <module>
    tclversion_detailed = tkinter.Tcl().eval('info patchlevel')
  File "/var/folders/y3/8xn_btkd7476nynq0r29rv7r0000gn/T//onefile_38144_1671365304_810716/tkinter/__init__.py", line 2372, in Tcl
  File "/var/folders/y3/8xn_btkd7476nynq0r29rv7r0000gn/T//onefile_38144_1671365304_810716/tkinter/__init__.py", line 2270, in __init__
_tkinter.TclError: Can't find a usable init.tcl in the following directories: 
    /Users/fangyao/opt/anaconda3/envs/videoEnv/lib/tcl8.6 /opt/homebrew/lib/tcl8.6 /opt/lib/tcl8.6 /opt/homebrew/library /opt/library /opt/tcl8.6.11/library /tcl8.6.11/library

**Comment by dfvips** [comment]
brew安装tcl提示
Warning: No available formula with the name "tcl". Did you mean tctl, tcc, tpl, tal, ucl, pcl, fcl, ecl or acl?
==> Searching for similarly named formulae...
These similarly named formulae were found:
atomist-cli         livekit-cli         tclap               tal
boot-clj            markdownlint-cli    vault-cli           ucl
fleet-cli           markdownlint-cli2   vtclock             pcl
git-cliff           openshift-cli       webtorrent-cli      fcl
grunt-cli           parquet-cli         tctl                ecl
homeassistant-cli   speedtest-cli       tcc                 acl
jimtcl              tcl-tk ✔            tpl

**Comment by YaoFANGUK** [comment]
mac版本的运行源码试试

**Comment by dfvips** [comment]
第一时间就试过了，不行。应该是有些不兼容arm架构。windows arm也无法运行。
