### ISSUE TITLE
I got this error when try to exacting sub

### ISSUE THREAD

**Issue by gozvn** [YaoFANGUK/video-subtitle-extractor#187]

**Comment by jiangliuer007** [comment]
我也遇到一样的问题。
成功打开视频：F:/aaa.ts
字幕区域：(452,580.0,54,1026)
识别字幕语言：ch
识别模式：fast
使用GPU进行加速
帧数：172583.0，帧率：23.976023976023978
【处理中】开启提取视频关键帧...
【处理中】开始提取字幕信息，此步骤可能花费较长时间，请耐心等待...
【结束】提取视频关键帧完毕...
【结束】完成字幕提取，生成原始字幕文件...
【处理中】开始生成字幕文件
Exception in thread Thread-3:
Traceback (most recent call last):
  File "F:\vse\Python\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "F:\vse\Python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "F:\vse\resources\gui.py", line 291, in task
    self.se.run()
  File "F:\vse\resources\backend\main.py", line 184, in run
    self.generate_subtitle_file_vsf()
  File "F:\vse\resources\backend\main.py", line 509, in generate_subtitle_file_vsf
    with open(self.vsf_subtitle, mode='r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\vse\\resources\\output\\aaa\\subtitle\\raw_vsf.srt'

我查看了output文件夹中，ILAImages ISAImages RGNAImages都是有部分图片的，subtitle里raw.txt有提取的字幕信息，其他文件夹为空。
不知道什么原因，求助

**Comment by jiangliuer007** [comment]
我也遇到一样的问题。
成功打开视频：F:/aaa.ts
字幕区域：(452,580.0,54,1026)
识别字幕语言：ch
识别模式：fast
使用GPU进行加速
帧数：172583.0，帧率：23.976023976023978
【处理中】开启提取视频关键帧...
【处理中】开始提取字幕信息，此步骤可能花费较长时间，请耐心等待...
【结束】提取视频关键帧完毕...
【结束】完成字幕提取，生成原始字幕文件...
【处理中】开始生成字幕文件
Exception in thread Thread-3:
Traceback (most recent call last):
  File "F:\vse\Python\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "F:\vse\Python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "F:\vse\resources\gui.py", line 291, in task
    self.se.run()
  File "F:\vse\resources\backend\main.py", line 184, in run
    self.generate_subtitle_file_vsf()
  File "F:\vse\resources\backend\main.py", line 509, in generate_subtitle_file_vsf
    with open(self.vsf_subtitle, mode='r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\vse\\resources\\output\\aaa\\subtitle\\raw_vsf.srt'

我查看了output文件夹中，ILAImages ISAImages RGNAImages都是有部分图片的，subtitle里raw.txt有提取的字幕信息，其他文件夹为空。
不知道什么原因，求助
