### ISSUE TITLE
系统找不到指定路劲

### ISSUE THREAD

**Issue by Linjiaoshou** [YaoFANGUK/video-subtitle-extractor#190]
成功打开视频：E:/2视频接单2/2023/2月/2月23日 提取/超级美男潘安 .mp4
选择视频字幕的语言: 简体中文
选择识别模式: 快速
字幕区域：(911,1080,96,1824)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\shipingyingzimutiqu\WINCPU\vse\threading.py", line 932, in _bootstrap_inner
  File "D:\shipingyingzimutiqu\WINCPU\vse\threading.py", line 870, in run
  File "D:\shipingyingzimutiqu\WINCPU\vse\gui.py", line 290, in task
  File "D:\shipingyingzimutiqu\WINCPU\vse\backend\main.py", line 89, in __init__
    os.makedirs(self.frame_output_dir)
  File "D:\shipingyingzimutiqu\WINCPU\vse\os.py", line 223, in makedirs
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'D:\\shipingyingzimutiqu\\WINCPU\\vse\\output\\超级美男潘安 \\frames'

这个应该怎么解决，之前还好用的，换了一台电脑也是这样 拜托指点

**Comment by Linjiaoshou** [comment]
找到原因了，我的视频文件名，有个空格，视频文件名中文没有关系，就是不能有空格和符号
