### ISSUE TITLE
./VideoSubFinderCli: error while loading shared libraries: libavcodec.so.58: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by sunzhaoyang** [YaoFANGUK/video-subtitle-extractor#205]
如果 `请指定字幕区域 (ymin ymax xmin xmax)：` 未指定，直接回车则正常识别

如果填写了值，例如`320 640 0 360`, 则会报如下错误：

```
请输入视频完整路径：/tmp/test.flv
请指定字幕区域 (ymin ymax xmin xmax)：320 640 0 360
识别字幕语言：ch
识别模式：fast
使用GPU进行加速
帧数：2548.0，帧率：30.00011773986554
【处理中】开启提取视频关键帧...
./VideoSubFinderCli: error while loading shared libraries: libavcodec.so.58: cannot open shared object file: No such file or directory
【处理中】开始提取字幕信息，此步骤可能花费较长时间，请耐心等待...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 2548/2548 [00:01<00:00, 2135.50it/s]
【结束】提取视频关键帧完毕...                                                                                                | 0/2548 [00:00<?, ?it/s]
【结束】完成字幕提取，生成原始字幕文件...
【处理中】开始生成字幕文件
Traceback (most recent call last):
  File "./backend/main.py", line 1039, in <module>
    se.run()
  File "./backend/main.py", line 184, in run
    self.generate_subtitle_file_vsf()
  File "./backend/main.py", line 552, in generate_subtitle_file_vsf
    with open(self.vsf_subtitle, mode='r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/video-subtitle-extractor/output/test/subtitle/raw_vsf.srt'
```

**Comment by sunzhaoyang** [comment]
貌似是因为 Ubuntu 版本不够高，18.04 只能装到 7:3.4.11，包里是 libavcodec.so.57

**Comment by eritpchy** [comment]
自行编译 https://github.com/eritpchy/videosubfinder-cli

**Comment by YaoFANGUK** [comment]
查看libavcodec安装目录：
```shell
whereis libavcodec.so
```

如果输出：
> libavcodec: /usr/lib/x86_64-linux-gnu/libavcodec.so /usr/lib/x86_64-linux-gnu/libavcodec.a

则说明安装了libavcodec.so, 如果没有则自行搜索安装libavcodec

查看安装版本：
```shell
ls /usr/lib/x86_64-linux-gnu/ | grep 
```
> libavcodec.a
libavcodec.so
libavcodec.so.57
libavcodec.so.57.107.100
libavcodec.so.58
libavcodec.so.58.54.100

根据安装的版本做软链接：
```shell
sudo ln -s libavcodec.so.58.54.100 libavcodec.so.58
```
