### ISSUE TITLE
Error: Can not import avx core while this file exists: D:\subtitle\python-3.7.0\lib\site-packages\paddle\fluid\core_avx.pyd

### ISSUE THREAD

**Issue by IndustriousSnail** [YaoFANGUK/video-subtitle-extractor#21]
打开exe无反应，通过 `run.bat` 可以看到有如下报错

```
D:\subtitle>python-3.7.0\python.exe src\gui.py
Error: Can not import avx core while this file exists: D:\subtitle\python-3.7.0\lib\site-packages\paddle\fluid\core_avx.pyd
Traceback (most recent call last):
  File "src\gui.py", line 19, in <module>
    import config
  File "src\config.py", line 12, in <module>
    from paddle import fluid
  File "D:\subtitle\python-3.7.0\lib\site-packages\paddle\__init__.py", line 29, in <module>
    from .fluid import monkey_patch_variable
  File "D:\subtitle\python-3.7.0\lib\site-packages\paddle\fluid\__init__.py", line 35, in <module>
    from . import framework
  File "D:\subtitle\python-3.7.0\lib\site-packages\paddle\fluid\framework.py", line 36, in <module>
    from . import core
  File "D:\subtitle\python-3.7.0\lib\site-packages\paddle\fluid\core.py", line 289, in <module>
    raise e
  File "D:\subtitle\python-3.7.0\lib\site-packages\paddle\fluid\core.py", line 254, in <module>
    from .core_avx import *
ImportError: DLL load failed: 找不到指定的模块。
```

环境如下：

版本：vse_windows_CPU.zip

```
OS 名称:          Microsoft Windows 10 家庭中文版
OS 版本:          10.0.19042 暂缺 Build 19042
系统型号:         20T6A002CD
系统类型:         x64-based PC
处理器:           安装了 1 个处理器。
                  [01]: AMD64 Family 23 Model 96 Stepping 1 AuthenticAMD ~2000 Mhz
BIOS 版本:        LENOVO R1AET37W (1.13 ), 2021/4/9
修补程序:         安装了 9 个修补程序。
                  [01]: KB5003254
                  [02]: KB4534170
                  [03]: KB4537759
                  [04]: KB4545706
                  [05]: KB4562830
                  [06]: KB4577266
                  [07]: KB4580325
                  [08]: KB5004945
                  [09]: KB5003742
Hyper-V 要求:     虚拟机监视器模式扩展: 是
                  固件中已启用虚拟化: 是
                  二级地址转换: 是
                  数据执行保护可用: 是
```

**Comment by YaoFANGUK** [comment]
安装： Microsoft Visual C++ 2017 Redistributable安装方法：https://social.msdn.microsoft.com/Forums/vstudio/en-US/e653a57a-bc32-4134-87bf-df33058f0531/download-microsoft-visual-c-2017-redistributable

参考： https://github.com/PaddlePaddle/Paddle/issues/28205

**Comment by DizzyTom** [comment]
类似的错误，但是我的程序pyd出现在了临时文件中，换了Microsoft Visual C++ 2017 Redistributable也一样。
`Error: Can not import avx core while this file exists: C:\Users\30388\AppData\Local\Temp\_MEI79762\paddle\fluid\core_avx.pyd
Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "utils.py", line 5, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddleocr\__init__.py", line 15, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddleocr\paddleocr.py", line 20, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddle\__init__.py", line 25, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddle\fluid\__init__.py", line 36, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddle\fluid\framework.py", line 37, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "paddle\fluid\core.py", line 294, in <module>
  File "paddle\fluid\core.py", line 256, in <module>
ImportError: DLL load failed: 找不到指定的模块。
[2952] Failed to execute script 'main' due to unhandled exception!`
