### ISSUE TITLE
Google Collab error

### ISSUE THREAD

**Issue by callista13** [YaoFANGUK/video-subtitle-extractor#221]
How should I go about the below error?

`!pip install -r requirements_gpu.txt`

![image](https://github.com/YaoFANGUK/video-subtitle-extractor/assets/104643877/294ff99e-c8bc-4b36-9e75-731c26726af9)

**Comment by callista13** [comment]
I also tried with the .exe and getting another error.
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\cc\AppData\Local\Temp\ON3C05~1\threading.py", line 932, in _bootstrap_inner
  File "C:\Users\cc\AppData\Local\Temp\ON3C05~1\threading.py", line 870, in run
  File "C:\Users\cc\AppData\Local\Temp\ON3C05~1\gui.py", line 291, in task
  File "C:\Users\cc\AppData\Local\Temp\ON3C05~1\backend\main.py", line 184, in run
    self.generate_subtitle_file_vsf()
  File "C:\Users\cc\AppData\Local\Temp\ON3C05~1\backend\main.py", line 509, in generate_subtitle_file_vsf
    with open(self.vsf_subtitle, mode='r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\cc\\AppData\\Local\\Temp\\ON3C05~1\\output\\tes\\subtitle\\raw_vsf.srt'
```
