### ISSUE TITLE
this main.py not

### ISSUE THREAD

**Issue by momoko2806** [YaoFANGUK/video-subtitle-extractor#23]
This main.py not running 

(videoEnv) C:\Users\dangh>cd test

(videoEnv) C:\Users\dangh\test>cd video-subtitle-extractor

(videoEnv) C:\Users\dangh\test\video-subtitle-extractor>python main.py
Running Verify Fluid Program ...
W0818 00:52:55.951086  4356 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.4, Runtime API Version: 10.2
W0818 00:52:55.955085  4356 device_context.cc:422] device: 0, cuDNN Version: 7.6.
Your Paddle Fluid works well on SINGLE GPU or CPU.
Your Paddle Fluid works well on MUTIPLE GPU or CPU.
Your Paddle Fluid is installed successfully! Let's start deep Learning with Paddle Fluid now
使用GPU进行加速
请输入视频完整路径：8
帧数：0.0，帧率：0.0
【处理中】开启提取视频关键帧...
【结束】提取视频关键帧完毕...
【处理中】开始提取字幕信息，此步骤可能花费较长时间，请耐心等待...
I0818 00:53:09.134364  4356 analysis_config.cc:424] use_dlnne_:0
I0818 00:53:09.134364  4356 analysis_config.cc:424] use_dlnne_:0
I0818 00:53:09.134364  4356 analysis_config.cc:424] use_dlnne_:0
I0818 00:53:09.134364  4356 analysis_config.cc:424] use_dlnne_:0
【结束】完成字幕提取，生成原始字幕文件...
【处理中】开始检测并过滤水印区域内容
视频是否存在水印区域，存在的话输入y，不存在的话输入n: y
Traceback (most recent call last):
  File "main.py", line 809, in <module>
    se.run()
  File "main.py", line 106, in run
    self.filter_watermark()
  File "main.py", line 287, in filter_watermark
    random.choice(
  File "C:\ProgramData\Anaconda3\envs\videoEnv\lib\random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
how to fix this code, please help me creat file demo.py

**Comment by YaoFANGUK** [comment]
It is running. If you want graphic interface, you can run ```gui.py```, which is recommended.
