### ISSUE TITLE
OSError: (External) CUDA error(3), initialization error.  怎么解决呢？

### ISSUE THREAD

**Issue by acelxiao** [YaoFANGUK/video-subtitle-extractor#237]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/hakwing/miniconda3/envs/videoEnv/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/hakwing/miniconda3/envs/videoEnv/lib/python3.8/threading.py", line 870, in run

  0%|                                                                                                                                                 | 0/3765 [00:00<?, ?it/s]  File "/home/hakwing/acelxiao/video-subtitle-extractor/./backend/tools/subtitle_ocr.py", line 131, in ocr_task_consumer
    text_recogniser = OcrRecogniser()
  File "/home/hakwing/acelxiao/video-subtitle-extractor/./backend/tools/ocr.py", line 13, in __init__
    self.recogniser = self.init_model()
  File "/home/hakwing/acelxiao/video-subtitle-extractor/./backend/tools/ocr.py", line 96, in init_model
    return TextSystem(self.args)
  File "/home/hakwing/acelxiao/video-subtitle-extractor/./backend/tools/infer/predict_system.py", line 46, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "/home/hakwing/acelxiao/video-subtitle-extractor/./backend/tools/infer/predict_det.py", line 119, in __init__
    self.predictor, self.input_tensor, self.output_tensors, self.config = utility.create_predictor(
  File "/home/hakwing/acelxiao/video-subtitle-extractor/./backend/tools/infer/utility.py", line 312, in create_predictor
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3765/3765 [00:00<00:00, 6306531.37it/s]
    predictor = inference.create_predictor(config)
OSError: (External) CUDA error(3), initialization error. 
  [Hint: Please search for the error code(3) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:172)

以下是本机显卡 cuda信息:
$ nvidia-smi
Wed Oct 11 19:27:12 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   40C    P0    34W / 160W |      0MiB /  8192MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Mon_Oct_24_19:12:58_PDT_2022
Cuda compilation tools, release 12.0, V12.0.76
Build cuda_12.0.r12.0/compiler.31968024_0

**Comment by YaoFANGUK** [comment]
照着教程装一下cuda，要装11.7 不是12

**Comment by acelxiao** [comment]
> 照着教程装一下cuda，要装11.7 不是12

FileNotFoundError: [Errno 2] No such file or directory: '/data/video-subtitle-extractor/output/test/subtitle/raw_vsf.srt'  又报这个是为什么呢 需要先建这个文件？

**Comment by YaoFANGUK** [comment]
不是哦 这个是运行过程中自动生成了 看下是不是这个目录没有写权限

**Comment by alexwanglei** [comment]
遇到同样的问题，大佬帮忙看看

**Comment by alexwanglei** [comment]
找到原因了，忘了加这个了：multiprocessing.set_start_method("spawn")
