### ISSUE TITLE
GPU 該如何運行

### ISSUE THREAD

**Issue by beez19** [YaoFANGUK/video-subtitle-extractor#25]
你好, 我已經跟著步驟到要安裝依賴,
可是出現
(videoEnv) C:\Users\Bee>pip install -r requirements_gpu.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements_gpu.txt'

然後不知道如何繼續下去了

**Comment by YaoFANGUK** [comment]
> 你好, 我已經跟著步驟到要安裝依賴,
> 可是出現
> (videoEnv) C:\Users\Bee>pip install -r requirements_gpu.txt
> ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements_gpu.txt'
> 
> 然後不知道如何繼續下去了

你应该切换工作目录在requirements.txt文件夹下再运行该命令

**Comment by beez19** [comment]
請問如何切換?因爲第一次接觸

**Comment by YaoFANGUK** [comment]
使用cd命令

**Comment by beez19** [comment]
要如何寫?

**Comment by YaoFANGUK** [comment]
假如你的requirements_gpu.txt存在放在路径 C:\Users\Bee\video-subtitle-extractor-main下
你就输入```cd  C:\Users\Bee\video-subtitle-extractor-main```切换到这个目录下

**Comment by beez19** [comment]
我在另一個電腦成功切換,安裝了依賴文件,然後要運行 gui ... 以下問題出現
(videoEnv) C:\Users\user1\Downloads\New folder\video-subtitle-extractor-main>python gui.py
W0830 12:15:47.823812 40124 init.cc:141] Compiled with WITH_GPU, but no GPU found in runtime.
C:\Users\user1\anaconda3\envs\videoEnv\lib\site-packages\paddle\fluid\framework.py:298: UserWarning: You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.
  warnings.warn(
Running Verify Fluid Program ...
WARNING:root:You are using GPU version Paddle Fluid, But Your CUDA Device is not set properly
 Original Error is (External)  Cuda error(35), CUDA driver version is insufficient for CUDA runtime version.
  [Advise: This indicates that the installed NVIDIA CUDA driver is older than the CUDA runtime library. This is not a supported configuration.Users should install an updated NVIDIA display driver to allow the application to run.] (at C:\home\workspace\Paddle_release\paddle\fluid\platform\gpu_info.cc:99)

Traceback (most recent call last):
  File "gui.py", line 14, in <module>
    import config
  File "C:\Users\user1\Downloads\New folder\video-subtitle-extractor-main\config.py", line 66, in <module>
    if len(fluid.cuda_places()) > 0:
  File "C:\Users\user1\anaconda3\envs\videoEnv\lib\site-packages\paddle\fluid\framework.py", line 442, in cuda_places
    device_ids = _cuda_ids()
  File "C:\Users\user1\anaconda3\envs\videoEnv\lib\site-packages\paddle\fluid\framework.py", line 357, in _cuda_ids
    device_ids = six.moves.range(core.get_cuda_device_count())
OSError: (External)  Cuda error(35), CUDA driver version is insufficient for CUDA runtime version.
  [Advise: This indicates that the installed NVIDIA CUDA driver is older than the CUDA runtime library. This is not a supported configuration.Users should install an updated NVIDIA display driver to allow the application to run.] (at C:\home\workspace\Paddle_release\paddle\fluid\platform\gpu_info.cc:99)


(videoEnv) C:\Users\user1\Downloads\New folder\video-subtitle-extractor-main>

**Comment by YaoFANGUK** [comment]
你没安装显卡 或者你显卡不是nvidia的显卡 或者你没安装显卡依赖的环境

**Comment by beez19** [comment]
(videoEnv) C:\Users\Bee\Downloads\video-subtitle-extractor-main>python gui.py
Running Verify Fluid Program ...
Your Paddle Fluid works well on SINGLE GPU or CPU.
W0830 14:53:20.626885 18824 build_strategy.cc:171] fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU.
W0830 14:53:20.627882 18824 build_strategy.cc:430] fuse_bn_add_act_pass is only supported on GPU, skipped.
W0830 14:53:20.628908 18824 fuse_all_reduce_op_pass.cc:79] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 1.
Your Paddle Fluid works well on MUTIPLE GPU or CPU.
Your Paddle Fluid is installed successfully! Let's start deep Learning with Paddle Fluid now
Traceback (most recent call last):
  File "gui.py", line 16, in <module>
    from main import SubtitleExtractor
  File "C:\Users\Bee\Downloads\video-subtitle-extractor-main\main.py", line 21, in <module>
    from backend.tools.infer.predict_system import TextSystem
  File "C:\Users\Bee\Downloads\video-subtitle-extractor-main\backend\tools\infer\predict_system.py", line 30, in <module>
    import tools.infer.predict_det as predict_det
  File "C:\Users\Bee\Downloads\video-subtitle-extractor-main\backend\tools\infer\predict_det.py", line 31, in <module>
    from ppocr.data import create_operators, transform
  File "C:\Users\Bee\Downloads\video-subtitle-extractor-main\backend\ppocr\data\__init__.py", line 34, in <module>
    from ppocr.data.imaug import transform, create_operators
  File "C:\Users\Bee\Downloads\video-subtitle-extractor-main\backend\ppocr\data\imaug\__init__.py", line 20, in <module>
    from .make_border_map import MakeBorderMap
  File "C:\Users\Bee\Downloads\video-subtitle-extractor-main\backend\ppocr\data\imaug\make_border_map.py", line 13, in <module>
    from shapely.geometry import Polygon
  File "C:\Users\Bee\anaconda3\envs\videoEnv\lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "C:\Users\Bee\anaconda3\envs\videoEnv\lib\site-packages\shapely\geometry\base.py", line 19, in <module>
    from shapely.coords import CoordinateSequence
  File "C:\Users\Bee\anaconda3\envs\videoEnv\lib\site-packages\shapely\coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "C:\Users\Bee\anaconda3\envs\videoEnv\lib\site-packages\shapely\geos.py", line 154, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
  File "C:\Users\Bee\anaconda3\envs\videoEnv\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\Bee\anaconda3\envs\videoEnv\Library\bin\geos_c.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by beez19** [comment]
我再換電腦 , 有1050ti 的...結果不可以運行, 請問什麽問題?

**Comment by YaoFANGUK** [comment]
geos_c.dll的报错在readme里面有写：

```
2. Windows下出现geos_c.dll错误
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
  File "C:\Users\Flavi\anaconda3\envs\subEnv\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。
解决方案：

卸载Shapely
pip uninstall Shapely -y
使用conda重新安装Shapely
conda install Shapely
```

**Comment by beez19** [comment]
> geos_c.dll的报错在readme里面有写：
> 
> ```
> 2. Windows下出现geos_c.dll错误
>     _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
>   File "C:\Users\Flavi\anaconda3\envs\subEnv\lib\ctypes\__init__.py", line 364, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: [WinError 126] 找不到指定的模块。
> 解决方案：
> 
> 卸载Shapely
> pip uninstall Shapely -y
> 使用conda重新安装Shapely
> conda install Shapely
> ```

原來是這個問題, 謝謝, 可以運行了

**Comment by YaoFANGUK** [comment]
不客气 祝您生活愉快
