### ISSUE TITLE
No such file or directory: 'raw_vsf.srt'

### ISSUE THREAD

**Issue by julian0703** [YaoFANGUK/video-subtitle-extractor#268]
CUDA 11.8 出現這個錯誤
更新為11.7還是報錯
請問我有什麼遺漏的地方嗎？

> 選擇視頻字幕的語言: 繁體中文
選擇識別模式: 自動
字幕區域：(842,1069,96,1824)
識別字幕語言：chinese_cht
識別模式：auto
使用GPU進行加速
幀數：82421.0，幀率：29.97002997002997
V4-ch_det
V3-chinese_cht_rec_fast
【處理中】開啟提取視頻關鍵幀...
【處理中】開始提取字幕信息，此步驟可能花費較長時間，請耐心等待...
【結束】提取視頻關鍵幀完畢...
【結束】完成字幕提取，生成原始字幕文件...
【處理中】開始生成字幕文件
Exception in thread Thread-3:
Traceback (most recent call last):
  File "D:\Program\vse\Python\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\Program\vse\Python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Program\vse\resources\gui.py", line 316, in task
    self.se.run()
  File "D:\Program\vse\resources\backend\main.py", line 182, in run
    self.generate_subtitle_file_vsf()
  File "D:\Program\vse\resources\backend\main.py", line 595, in generate_subtitle_file_vsf
    subs = pysrt.open(self.vsf_subtitle)
  File "D:\Program\vse\Python\Lib\site-packages\pysrt\srtfile.py", line 151, in open
    source_file, encoding = cls._open_unicode_file(path, claimed_encoding=encoding)
  File "D:\Program\vse\Python\Lib\site-packages\pysrt\srtfile.py", line 292, in _open_unicode_file
    encoding = claimed_encoding or cls._detect_encoding(path)
  File "D:\Program\vse\Python\Lib\site-packages\pysrt\srtfile.py", line 279, in _detect_encoding
    file_descriptor = open(path, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Program\\vse\\resources\\output\\06\\subtitle\\raw_vsf.srt'

**Comment by julian0703** [comment]
1. 把ts用ffmpeg轉成mkv
`ffmpeg -i 02.ts -c:v copy -c:a copy 02.mkv`

2. 將原本安裝的Python 3.10移除即可
