### ISSUE TITLE
GPU版本报错无法启动（是N卡）

### ISSUE THREAD

**Issue by FTLDove** [YaoFANGUK/video-subtitle-extractor#290]
E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse>"./Python/python.exe" -c "import sys;sys.path.append('./Python');sys.path.append('./Python/Lib');sys.path.append('./Python/Lib/site-packages');sys.path.append('./Python/Scripts');import qpt.run as run"
2024-01-09 17:39:29,834 WARNING: E:\系统缓存\QPT_Cache_V/1.0b3.dev7中 系 字符会可能影响使用。
2024-01-09 17:39:29,835 WARNING: 当前系统的用户名中包含中文/空格等可能会对程序造成异常的字符，现已默认QPT临时目录为C:/q_tmp
E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\Python\Lib\site-packages\_distutils_hack\__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
2024-01-09 17:39:30,168 INFO: QPT Runtime版本号为1.0b3.dev7，若无法使用该程序，可向程序发布者或GitHub: QPT-Family/QPT提交issue寻求帮助
2024-01-09 17:39:30,706 INFO: 初次使用将会适应本地环境，可能需要几分钟时间，请耐心等待...
初始化进度 17:398/8  |━━━━━━━━━━━━━━━━━━━━| 100.00% 初始化完毕2024-01-09 17:39:30,714 INFO: 7:39:30,714 INFO: O:
2024-01-09 17:39:30,714 INFO: ----------WARNING SUMMARY
2024-01-09 17:39:30,714 INFO: 0|E:\系统缓存\QPT_Cache_V/1.0b3.dev7中 系 字符会可能影响使用。

2024-01-09 17:39:30,714 INFO: 1|当前系统的用户名中包含中文/空格等可能会对程序造成异常的字符，现已默认QPT临时目录为C:/q_tmp

2024-01-09 17:39:30,714 INFO: ----------ERROR SUMMARY
2024-01-09 17:39:30,714 INFO: ----------生成状态WARNING:2 ERROR:0
PS E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse> cd "E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\resources";./../Python/python.exe "E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\resources\gui.py" ; echo "---QPT OUTPUT STATUS CODE---" $?
Traceback (most recent call last):
  File "E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\resources\gui.py", line 8, in <module>
    import backend.main
  File "E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\resources\backend\main.py", line 27, in <module>
    from tools.infer.predict_det import TextDetector
  File "E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\resources\backend\tools\infer\predict_det.py", line 31, in <module>
    from ppocr.data import create_operators, transform
  File "E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\resources\backend\ppocr\data\__init__.py", line 35, in <module>
    from ppocr.data.imaug import transform, create_operators
  File "E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\resources\backend\ppocr\data\imaug\__init__.py", line 19, in <module>
    from .iaa_augment import IaaAugment
  File "E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\resources\backend\ppocr\data\imaug\iaa_augment.py", line 24, in <module>
    import imgaug
  File "E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\Python\Lib\site-packages\imgaug\__init__.py", line 7, in <module>
    from imgaug.imgaug import *  # pylint: disable=redefined-builtin
  File "E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\Python\Lib\site-packages\imgaug\imgaug.py", line 23, in <module>
    import skimage.measure
  File "E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\Python\Lib\site-packages\skimage\measure\__init__.py", line 6, in <module>
    from ._polygon import approximate_polygon, subdivide_polygon
  File "E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\Python\Lib\site-packages\skimage\measure\_polygon.py", line 2, in <module>
    from scipy import signal
  File "E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\Python\Lib\site-packages\scipy\signal\__init__.py", line 331, in <module>
    from ._peak_finding import *
  File "E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\Python\Lib\site-packages\scipy\signal\_peak_finding.py", line 8, in <module>
    from scipy.stats import scoreatpercentile
  File "E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\Python\Lib\site-packages\scipy\stats\__init__.py", line 468, in <module>
    from ._rvs_sampling import rvs_ratio_uniforms, NumericalInverseHermite  # noqa
  File "E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\Python\Lib\site-packages\scipy\stats\_rvs_sampling.py", line 3, in <module>
    from ._unuran import unuran_wrapper
  File "unuran_wrapper.pyx", line 221, in init scipy.stats._unuran.unuran_wrapper
  File "unuran_wrapper.pyx", line 200, in scipy.stats._unuran.unuran_wrapper._setup_unuran
  File "messagestream.pyx", line 36, in scipy._lib.messagestream.MessageStream.__cinit__
OSError: Failed to open file b'E:\\\xe7\xb3\xbb\xe7\xbb\x9f\xe7\xbc\x93\xe5\xad\x98\\scipy-nkvw1uqj'
2024-01-09 17:39:33,822 ERROR: 在执行终端命令时检测到了失败，完整信息如下：
PS E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse> cd "E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\resources";./../Python/python.exe "E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\resources\gui.py" ; echo "---QPT OUTPUT STATUS CODE---" $?
Traceback (most recent call last):
  File "E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\resources\gui.py", line 8, in <module>
    import backend.main
  File "E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\resources\backend\main.py", line 27, in <module>
    from tools.infer.predict_det import TextDetector
  File "E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\resources\backend\tools\infer\predict_det.py", line 31, in <module>
    from ppocr.data import create_operators, transform
  File "E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\resources\backend\ppocr\data\__init__.py", line 35, in <module>
    from ppocr.data.imaug import transform, create_operators
  File "E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\resources\backend\ppocr\data\imaug\__init__.py", line 19, in <module>
    from .iaa_augment import IaaAugment
  File "E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\resources\backend\ppocr\data\imaug\iaa_augment.py", line 24, in <module>
    import imgaug
  File "E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\Python\Lib\site-packages\imgaug\__init__.py", line 7, in <module>
    from imgaug.imgaug import *  # pylint: disable=redefined-builtin
  File "E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\Python\Lib\site-packages\imgaug\imgaug.py", line 23, in <module>
    import skimage.measure
  File "E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\Python\Lib\site-packages\skimage\measure\__init__.py", line 6, in <module>
    from ._polygon import approximate_polygon, subdivide_polygon
  File "E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\Python\Lib\site-packages\skimage\measure\_polygon.py", line 2, in <module>
    from scipy import signal
  File "E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\Python\Lib\site-packages\scipy\signal\__init__.py", line 331, in <module>
    from ._peak_finding import *
  File "E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\Python\Lib\site-packages\scipy\signal\_peak_finding.py", line 8, in <module>
    from scipy.stats import scoreatpercentile
  File "E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\Python\Lib\site-packages\scipy\stats\__init__.py", line 468, in <module>
    from ._rvs_sampling import rvs_ratio_uniforms, NumericalInverseHermite  # noqa
  File "E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse\Python\Lib\site-packages\scipy\stats\_rvs_sampling.py", line 3, in <module>
    from ._unuran import unuran_wrapper
  File "unuran_wrapper.pyx", line 221, in init scipy.stats._unuran.unuran_wrapper
  File "unuran_wrapper.pyx", line 200, in scipy.stats._unuran.unuran_wrapper._setup_unuran
  File "messagestream.pyx", line 36, in scipy._lib.messagestream.MessageStream.__cinit__
OSError: Failed to open file b'E:\\\xe7\xb3\xbb\xe7\xbb\x9f\xe7\xbc\x93\xe5\xad\x98\\scipy-nkvw1uqj'

E:\BaiduNetdiskDownload\vse_windows_gpu_v2.0.0\vse>pause
Press any key to continue . . .

**Comment by LING2024ing** [comment]
我也遇到同样的问题，请问你解决了吗？

**Comment by shiming-miku** [comment]
我也遇到同样问题，请问有解决吗

> 我也遇到同样的问题，请问你解决了吗？

**Comment by LING2024ing** [comment]
用剪映，不用这个了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2025年3月8日(星期六) 下午2:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [YaoFANGUK/video-subtitle-extractor] GPU版本报错无法启动（是N卡） (Issue #290)












   
我也遇到同样问题，请问有解决吗
  
我也遇到同样的问题，请问你解决了吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  shiming-miku left a comment (YaoFANGUK/video-subtitle-extractor#290)
 
我也遇到同样问题，请问有解决吗
  
我也遇到同样的问题，请问你解决了吗？

**Comment by shiming-miku** [comment]
我注意到是我的电脑环境变量的TEMP，TMP目录带有中文，更换了个没有中文的目录后可以了

**Comment by shiming-miku** [comment]
> 用剪映，不用这个了
> […](#)
我注意到是我的电脑环境变量的TEMP，TMP目录带有中文，更换了个没有中文的目录后可以了
