### ISSUE TITLE
ubantu 18.04  《Failed to load the native TensorFlow runtime》

### ISSUE THREAD

**Issue by RodJohn** [YaoFANGUK/video-subtitle-extractor#3]
环境 ：ubantu 18.04 
安装 ：pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/
问题 ：
(vw)  python ./main/demo.py
Traceback (most recent call last):
  File "/home/bigdata/anaconda3/envs/vw/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/bigdata/anaconda3/envs/vw/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/bigdata/anaconda3/envs/vw/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/bigdata/anaconda3/envs/vw/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/bigdata/anaconda3/envs/vw/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/bigdata/anaconda3/envs/vw/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: invalid ELF header

**Comment by YaoFANGUK** [comment]
tensorflow的版本不对, 先pip uninstall tensorflow. 然后<a href="https://files.pythonhosted.org/packages/86/9f/be0165c6eefd841e6928e54d3d083fa174f92d640fdc52f73a33dc9c54d1/tensorflow-1.4.0-cp36-cp36m-manylinux1_x86_64.whl">下载tensorflow-1.4.0-cp36-cp36m-manylinux1_x86_64</a> 然后切换到下载目录pip install tensorflow-1.4.0-cp36-cp36m-manylinux1_x86_64.whl
