### ISSUE TITLE
please FIX this error

### ISSUE THREAD

**Issue by tom2k3** [YaoFANGUK/video-subtitle-extractor#310]
![Screenshot 2024-05-14 222700](https://github.com/YaoFANGUK/video-subtitle-extractor/assets/28794975/5f46b8c8-056e-48db-90e2-4064b7777279)

Exception in thread Thread-1:
Traceback (most recent call last):
  File "I:\BaiduNetdiskDownload\vse_windows_cpu_v2.0.0\vse\threading.py", line 932, in _bootstrap_inner
  File "I:\BaiduNetdiskDownload\vse_windows_cpu_v2.0.0\vse\threading.py", line 870, in run
  File "I:\BaiduNetdiskDownload\vse_windows_cpu_v2.0.0\vse\gui.py", line 313, in task
  File "I:\BaiduNetdiskDownload\vse_windows_cpu_v2.0.0\vse\backend\main.py", line 174, in run
    self.generate_subtitle_file_vsf()
  File "I:\BaiduNetdiskDownload\vse_windows_cpu_v2.0.0\vse\backend\main.py", line 539, in generate_subtitle_file_vsf
    with open(self.vsf_subtitle, mode='r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'I:\\BaiduNetdiskDownload\\vse_windows_cpu_v2.0.0\\vse\\output\\幸福Battle - 第01集 - 韓劇網\\subtitle\\raw_vsf.srt'

**Comment by molitar** [comment]
Same error and I see previous threads on this but whoever designs this tool does not want to seem to reply on how to fix!  So seems this tool is horribly supported!

**Comment by tom2k3** [comment]
> Same error and I see previous threads on this but whoever designs this tool does not want to seem to reply on how to fix! So seems this tool is horribly supported!

**nvm，for this video title i find the problem at where but others title i not sure same or not，the capture position will different position when reach advertise，maybe convert problem，the guys direct combine movie and advertise so have 2 different resolution in same file。
so i just cut out the part advertise(or find another source without that advertise)，now done extract the subtitles。**

![Screenshot 2024-05-17 153328](https://github.com/YaoFANGUK/video-subtitle-extractor/assets/28794975/f116e298-fba5-44e4-87bd-6d53d2a198d1)
![Screenshot 2024-05-17 153359](https://github.com/YaoFANGUK/video-subtitle-extractor/assets/28794975/38e28090-2142-47ce-94fa-f81eabc13b5c)
![2024-05-17 15-30-24](https://github.com/YaoFANGUK/video-subtitle-extractor/assets/28794975/44fd4045-dbd7-445b-be24-dc147cdc3271)
