### ISSUE TITLE
安装过程报错安装不了

### ISSUE THREAD

**Issue by KZ0000007** [YaoFANGUK/video-subtitle-extractor#313]
2024-05-22 20:33:02,702 ERROR: 在执行终端命令时检测到了失败，完整信息如下：
PS F:\ZIMU\vse_windows_GPU\vse> cd "F:\ZIMU\vse_windows_GPU\vse\resources";./../Python/python.exe "F:\ZIMU\vse_windows_GPU\vse\resources\gui.py" ; echo "---QPT OUTPUT STATUS CODE---" $?
Traceback (most recent call last):
  File "F:\ZIMU\vse_windows_GPU\vse\resources\gui.py", line 8, in <module>
    import backend.main
  File "F:\ZIMU\vse_windows_GPU\vse\resources\backend\main.py", line 28, in <module>
    from tools.infer.predict_det import TextDetector
  File "F:\ZIMU\vse_windows_GPU\vse\resources\backend\tools\infer\predict_det.py", line 31, in <module>
    from ppocr.data import create_operators, transform
  File "F:\ZIMU\vse_windows_GPU\vse\resources\backend\ppocr\data\__init__.py", line 35, in <module>
    from ppocr.data.imaug import transform, create_operators
  File "F:\ZIMU\vse_windows_GPU\vse\resources\backend\ppocr\data\imaug\__init__.py", line 19, in <module>
    from .iaa_augment import IaaAugment
  File "F:\ZIMU\vse_windows_GPU\vse\resources\backend\ppocr\data\imaug\iaa_augment.py", line 24, in <module>
    import imgaug
  File "F:\ZIMU\vse_windows_GPU\vse\Python\Lib\site-packages\imgaug\__init__.py", line 7, in <module>
    from imgaug.imgaug import *  # pylint: disable=redefined-builtin
  File "F:\ZIMU\vse_windows_GPU\vse\Python\Lib\site-packages\imgaug\imgaug.py", line 23, in <module>
    import skimage.measure
  File "F:\ZIMU\vse_windows_GPU\vse\Python\Lib\site-packages\skimage\measure\__init__.py", line 6, in <module>
    from ._polygon import approximate_polygon, subdivide_polygon
  File "F:\ZIMU\vse_windows_GPU\vse\Python\Lib\site-packages\skimage\measure\_polygon.py", line 2, in <module>
    from scipy import signal
  File "F:\ZIMU\vse_windows_GPU\vse\Python\Lib\site-packages\scipy\signal\__init__.py", line 331, in <module>
    from ._peak_finding import *
  File "F:\ZIMU\vse_windows_GPU\vse\Python\Lib\site-packages\scipy\signal\_peak_finding.py", line 8, in <module>
    from scipy.stats import scoreatpercentile
  File "F:\ZIMU\vse_windows_GPU\vse\Python\Lib\site-packages\scipy\stats\__init__.py", line 468, in <module>
    from ._rvs_sampling import rvs_ratio_uniforms, NumericalInverseHermite  # noqa
  File "F:\ZIMU\vse_windows_GPU\vse\Python\Lib\site-packages\scipy\stats\_rvs_sampling.py", line 3, in <module>
    from ._unuran import unuran_wrapper
  File "unuran_wrapper.pyx", line 221, in init scipy.stats._unuran.unuran_wrapper
  File "unuran_wrapper.pyx", line 200, in scipy.stats._unuran.unuran_wrapper._setup_unuran
  File "messagestream.pyx", line 36, in scipy._lib.messagestream.MessageStream.__cinit__
OSError: Failed to open file b'C:\\Users\\\xe6\x88\x91\xe7\x9a\x84\xe7\x94\xb5\xe8\x84\x91\\AppData\\Local\\Temp\\scipy-h1m7jirr'

**Comment by KZ0000007** [comment]
安装过程报错，安装不了

**Comment by shiming-miku** [comment]
请问下你解决了吗

**Comment by shiming-miku** [comment]
> 安装过程报错，安装不了

我注意到是我的电脑环境变量的TEMP，TMP目录带有中文，更换了个没有中文的目录后可以了
