### ISSUE TITLE
help, error 

### ISSUE THREAD

**Issue by kucingkembar** [YaoFANGUK/video-subtitle-extractor#329]
sorry for my bad english, 
when i use exe version:

```
D:\vse>"./Python/python.exe" -c "import sys;sys.path.append('./Python');sys.path.append('./Python/Lib');sys.path.append('./Python/Lib/site-packages');sys.path.append('./Python/Scripts');import qpt.run as run"
D:\vse\Python\Lib\site-packages\_distutils_hack\__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
2024-07-18 01:15:08,312 INFO: QPT Runtime版本号为1.0b3.dev7，若无法使用该程序，可向程序发布者或GitHub: QPT-Family/QPT提交issue寻求帮助
2024-07-18 01:15:13,509 INFO: 初次使用将会适应本地环境，可能需要几分钟时间，请耐心等待...
初始化进度      2/8  |━━━━━               | 25.00% QPTDependencyPackage部署中...2024-07-18 01:15:13,515 ERROR: [Errno 22] Invalid argument
初始化进度      4/8  |━━━━━━━━━━          | 50.00% PaddlePaddlePackage部署中...2024-07-18 01:15:13,517 ERROR: [Errno 22] Invalid argument
初始化进度      5/8  |━━━━━━━━━━━━        | 62.50% AutoRequirementsPackage部署中...2024-07-18 01:15:13,538 ERROR: [Errno 22] Invalid argument
初始化进度      6/8  |━━━━━━━━━━━━━━━     | 75.00% BatchInstallation部署中...2024-07-18 01:15:13,805 INFO: 需要补充的安装包数量为：45
2024-07-18 01:15:13,806 ERROR: [Errno 22] Invalid argument
2024-07-18 01:15:13,807 ERROR: [Errno 22] Invalid argument
2024-07-18 01:15:13,808 ERROR: [Errno 22] Invalid argument
2024-07-18 01:15:13,808 ERROR: [Errno 22] Invalid argument
2024-07-18 01:15:13,809 ERROR: [Errno 22] Invalid argument
2024-07-18 01:15:13,810 ERROR: [Errno 22] Invalid argument
2024-07-18 01:15:13,811 ERROR: [Errno 22] Invalid argument
2024-07-18 01:15:13,811 ERROR: [Errno 22] Invalid argument
2024-07-18 01:15:13,812 ERROR: [Errno 22] Invalid argument
2024-07-18 01:15:13,813 ERROR: [Errno 22] Invalid argument
2024-07-18 01:15:13,814 ERROR: [Errno 22] Invalid argument
2024-07-18 01:15:13,814 ERROR: [Errno 22] Invalid argument
2024-07-18 01:15:13,815 ERROR: [Errno 22] Invalid argument
2024-07-18 01:15:13,816 ERROR: [Errno 22] Invalid argument
2024-07-18 01:15:13,817 ERROR: [Errno 22] Invalid argument
2024-07-18 01:15:13,817 ERROR: [Errno 22] Invalid argument
2024-07-18 01:15:13,818 ERROR: [Errno 22] Invalid argument
2024-07-18 01:15:13,819 ERROR: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\vse\Python\Lib\site-packages\qpt\run.py", line 25, in <module>
    module.run()
  File "D:\vse\Python\Lib\site-packages\qpt\executor.py", line 472, in run
    self._solve_module()
  File "D:\vse\Python\Lib\site-packages\qpt\executor.py", line 427, in _solve_module
    render()
  File "D:\vse\Python\Lib\site-packages\qpt\executor.py", line 421, in render
    sub_module.unpack()
  File "D:\vse\Python\Lib\site-packages\qpt\modules\base.py", line 214, in unpack
    opt.run(op_path)
  File "D:\vse\Python\Lib\site-packages\qpt\modules\base.py", line 77, in run
    self.act()
  File "D:\vse\Python\Lib\site-packages\qpt\modules\package.py", line 173, in act
    QPT_MEMORY.pip_tool.install_local_package(os.path.join(self.packages_path, whl_name),
  File "D:\vse\Python\Lib\site-packages\qpt\kernel\qinterpreter.py", line 165, in install_local_package
    self.pip_package_shell(package=package,
  File "D:\vse\Python\Lib\site-packages\qpt\kernel\qinterpreter.py", line 121, in pip_package_shell
    self.pip_shell(str(opts))
  File "D:\vse\Python\Lib\site-packages\qpt\kernel\qinterpreter.py", line 89, in pip_shell
    self.pip_main(str(shell).split(" "))
  File "D:\vse\Python\Lib\site-packages\qpt\kernel\qinterpreter.py", line 41, in closure
    self.main_terminal.stdin.write(final_shell)
OSError: [Errno 22] Invalid argument
```
when use conda:
```
(videoEnv) D:\vse>python resources\gui.py
d:\Users\GIGABYTE\miniconda3\envs\videoEnv\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
d:\Users\GIGABYTE\miniconda3\envs\videoEnv\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
d:\Users\GIGABYTE\miniconda3\envs\videoEnv\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
Traceback (most recent call last):
  File "resources\gui.py", line 8, in <module>
    import backend.main
  File "D:\vse\resources\backend\main.py", line 24, in <module>
    import config
  File "D:\vse\resources\backend\config.py", line 16, in <module>
    from paddle import fluid
  File "d:\Users\GIGABYTE\miniconda3\envs\videoEnv\lib\site-packages\paddle\__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "d:\Users\GIGABYTE\miniconda3\envs\videoEnv\lib\site-packages\paddle\framework\__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "d:\Users\GIGABYTE\miniconda3\envs\videoEnv\lib\site-packages\paddle\framework\random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "d:\Users\GIGABYTE\miniconda3\envs\videoEnv\lib\site-packages\paddle\fluid\__init__.py", line 45, in <module>
    from . import dataset
  File "d:\Users\GIGABYTE\miniconda3\envs\videoEnv\lib\site-packages\paddle\fluid\dataset.py", line 19, in <module>
    from ..utils import deprecated
  File "d:\Users\GIGABYTE\miniconda3\envs\videoEnv\lib\site-packages\paddle\utils\__init__.py", line 26, in <module>
    from . import download  # noqa: F401
  File "d:\Users\GIGABYTE\miniconda3\envs\videoEnv\lib\site-packages\paddle\utils\download.py", line 23, in <module>
    import requests
  File "d:\Users\GIGABYTE\miniconda3\envs\videoEnv\lib\site-packages\requests\__init__.py", line 48, in <module>
    from charset_normalizer import __version__ as charset_normalizer_version
  File "d:\Users\GIGABYTE\miniconda3\envs\videoEnv\lib\site-packages\charset_normalizer\__init__.py", line 23, in <module>
    from charset_normalizer.api import from_fp, from_path, from_bytes, normalize
  File "d:\Users\GIGABYTE\miniconda3\envs\videoEnv\lib\site-packages\charset_normalizer\api.py", line 10, in <module>
    from charset_normalizer.md import mess_ratio
AttributeError: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
```
please somebody help me

**Comment by kucingkembar** [comment]
update : fix
1. make sure the current directory(cd) is in the [resources] folder where the [gui.py] located, then run [python gui.py]
2. if missing any package, do not pip install from [requirements.txt], try pip install from [opt\packages] first,
like this : pip install drive:\folder\opt\packages\missingpackage.whl
