### ISSUE TITLE
Linux 处理视频失败。

### ISSUE THREAD

**Issue by tuta-gh** [YaoFANGUK/video-subtitle-extractor#354]
成功打开视频：/home/etrade/softing/you-get/video/从马岛海战到南海对峙，美元是如何收割全世界的？.mp4
字幕区域：(374,475,43,810)
识别字幕语言：ch
识别模式：fast
帧数：59727.0，帧率：30.000010359639923
V4-ch_det_fast
V4-ch_rec_fast
【处理中】开启提取视频关键帧...
Segmentation fault (core dumped)
【处理中】开始提取字幕信息，此步骤可能花费较长时间，请耐心等待...
【结束】提取视频关键帧完毕...
【结束】完成字幕提取，生成原始字幕文件...
【处理中】开始生成字幕文件
Exception in thread Thread-2 (task):
Traceback (most recent call last):
  File "/home/etrade/softing/video-subtitle-extractor-main/.conda/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/home/etrade/softing/video-subtitle-extractor-main/.conda/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/home/etrade/softing/video-subtitle-extractor-main/gui.py", line 316, in task
    self.se.run()
  File "/home/etrade/softing/video-subtitle-extractor-main/backend/main.py", line 182, in run
    self.generate_subtitle_file_vsf()
  File "/home/etrade/softing/video-subtitle-extractor-main/backend/main.py", line 597, in generate_subtitle_file_vsf
    subs = pysrt.open(self.vsf_subtitle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/etrade/softing/video-subtitle-extractor-main/.conda/lib/python3.12/site-packages/pysrt/srtfile.py", line 151, in open
    source_file, encoding = cls._open_unicode_file(path, claimed_encoding=encoding)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/etrade/softing/video-subtitle-extractor-main/.conda/lib/python3.12/site-packages/pysrt/srtfile.py", line 292, in _open_unicode_file
    encoding = claimed_encoding or cls._detect_encoding(path)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/etrade/softing/video-subtitle-extractor-main/.conda/lib/python3.12/site-packages/pysrt/srtfile.py", line 279, in _detect_encoding
    file_descriptor = open(path, 'rb')
                      ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/etrade/softing/video-subtitle-extractor-main/output/从马岛海战到南海对峙，美元是如何收割全世界的？/subtitle/raw_vsf.srt'

**Comment by YaoFANGUK** [comment]
Segmentation fault (core dumped)
可以用dmesg看看什么原因

**Comment by eritpchy** [comment]
大概是vsf静态包不兼容该linux发行版

**Comment by 0x1001u** [comment]
这个原因是你设置了字幕区域,设了字幕区域后有gpu的情况下调用了extract_frame_by_vsf这个会用到VideoSubFinderCli,从仓库中clone回去的VideoSubFinderCli运行就会出现Segmentation fault.可能是兼容性问题,暂时没有测试.

**Comment by 0x1001u** [comment]
刚才抽空验证了一下.用[eritpchy](https://github.com/eritpchy) 大的 5.70.3替代就可以用了.https://github.com/eritpchy/videosubfinder-cli/releases

**Comment by FeiM2022** [comment]
参考以上各位大佬的方案，一开始我也遇到Segmentation fault (core dumped)的问题
尝试替换VideoSubFinderCli 为 5.70.3 无果，服务器版本：PRETTY_NAME="Ubuntu 24.04.1 LTS"
更新为：PRETTY_NAME="Ubuntu 22.04.4 LTS"后,

<img width="1079" height="180" alt="Image" src="https://github.com/user-attachments/assets/cd24d365-b871-4c02-92b2-39ed184d6e24" />

输入字幕区域后，可以正常提取了
