### ISSUE TITLE
無語了搞了一個晚上，太浪費時間了，怎麼到處都是BUG Error: Can not import paddle core while this file exists: /home/ps/anaconda3/envs/VSE/lib/python3.10/site-packages/paddle/base/libpaddle.so

### ISSUE THREAD

**Issue by BUAACY** [YaoFANGUK/video-subtitle-extractor#355]
Error: Can not import paddle core while this file exists: /home/ps/anaconda3/envs/VSE/lib/python3.10/site-packages/paddle/base/libpaddle.so
Traceback (most recent call last):
  File "/home/ps/code/VSE/./backend/main.py", line 24, in <module>
    import config
  File "/home/ps/code/VSE/./backend/config.py", line 16, in <module>
    import paddle
  File "/home/ps/anaconda3/envs/VSE/lib/python3.10/site-packages/paddle/__init__.py", line 28, in <module>
    from .base import core  # noqa: F401
  File "/home/ps/anaconda3/envs/VSE/lib/python3.10/site-packages/paddle/base/__init__.py", line 36, in <module>
    from . import core
  File "/home/ps/anaconda3/envs/VSE/lib/python3.10/site-packages/paddle/base/core.py", line 380, in <module>
    raise e
  File "/home/ps/anaconda3/envs/VSE/lib/python3.10/site-packages/paddle/base/core.py", line 268, in <module>
    from . import libpaddle
ImportError: /home/ps/anaconda3/envs/VSE/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/ps/anaconda3/envs/VSE/lib/python3.10/site-packages/paddle/base/libpaddle.so)

**Comment by YaoFANGUK** [comment]
GLIBCXX_3.4.30 说明你的glibc版本较低哦，要升级到3.4.30以上

**Comment by eritpchy** [comment]
百度的锅， 建议使用一键包

**Comment by fuxiaoiii** [comment]
> 百度的锅， 建议使用一键包

请问 一键包 在哪
