### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by Johndirr** [YaoFANGUK/video-subtitle-extractor#44]
When running the 启动程序.exe I get the following error after choosing the language and accuracy:
`Traceback (most recent call last):
  File "D:\vse_windows_GPU\vse\resources\gui.py", line 14, in <module>
    set_language_mode(os.path.join(os.path.dirname(__file__), 'settings.ini'))
  File "D:\vse_windows_GPU\vse\resources\backend\tools\settings.py", line 25, in set_language_mode
    print('\u9009\u62e9\u4e86:', values['-LANGUAGE-'])
  File "D:\vse_windows_GPU\vse\Python\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-2: character maps to <undefined>
2021-11-20 11:02:57,694 ERROR: 在执行终端命令时检测到了失败，完整信息如下：
PS D:\vse_windows_GPU\vse> cd "D:\vse_windows_GPU\vse\resources"; ./../Python/python.exe "D:\vse_windows_GPU\vse\resources\gui.py" ; echo "---QPT OUTPUT STATUS CODE---" $?
Traceback (most recent call last):
  File "D:\vse_windows_GPU\vse\resources\gui.py", line 14, in <module>
    set_language_mode(os.path.join(os.path.dirname(__file__), 'settings.ini'))
  File "D:\vse_windows_GPU\vse\resources\backend\tools\settings.py", line 25, in set_language_mode
    print('\u9009\u62e9\u4e86:', values['-LANGUAGE-'])
  File "D:\vse_windows_GPU\vse\Python\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-2: character maps to <undefined>`
Is there anything I can do to make this run?

**Comment by YaoFANGUK** [comment]
It seems like your operation system do not support chinese

**Comment by Johndirr** [comment]
Thanks for the information. I try to go with option 1.

> (1) delete all chinese character in .py files
Do you mean the .py files inside the resources folder? I have to translate the whole tool then.
> (2) install chinese language pack for your Windows.
This is no option since just installing the language pack won't make this work. I'd have to use chinese as the system language rendering me unable to navigate Windows.
