### ISSUE TITLE
Bug in start, KeyError, Language

### ISSUE THREAD

**Issue by latot** [YaoFANGUK/video-subtitle-extractor#61]
Hi hi, I try to run the app, but I get the next error:

```
python3 gui.py
Traceback (most recent call last):
  File "/home/pipe/Documentos/git/video-subtitle-extractor/gui.py", line 396, in <module>
    subtitleExtractorGUI = SubtitleExtractorGUI()
  File "/home/pipe/Documentos/git/video-subtitle-extractor/gui.py", line 20, in __init__
    LanguageModeGUI().run()
  File "/home/pipe/Documentos/git/video-subtitle-extractor/gui.py", line 261, in run
    self._interface_event_handler(event, values)
  File "/home/pipe/Documentos/git/video-subtitle-extractor/gui.py", line 356, in _interface_event_handler
    self.set_config(self.config_file, values['-INTERFACE-'], config['DEFAULT']['Language'],
  File "/usr/lib/python3.9/configparser.py", line 1257, in __getitem__
    raise KeyError(key)
KeyError: 'Language'
```

Edit, lack of information here, to reproduce, run the gui, go to language and select english, click ok the right button.

Thx.
```

**Comment by YaoFANGUK** [comment]
A bug here. I will fix it by tomorrow
